--
-- PostgreSQL database dump
--

-- Dumped from database version 12.2
-- Dumped by pg_dump version 12.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: actors; Type: TABLE; Schema: public; Owner: udacity
--

CREATE TABLE public.actors (
    id integer NOT NULL,
    name character varying NOT NULL,
    age integer NOT NULL,
    gender character varying NOT NULL
);


ALTER TABLE public.actors OWNER TO udacity;

--
-- Name: actors_id_seq; Type: SEQUENCE; Schema: public; Owner: udacity
--

CREATE SEQUENCE public.actors_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.actors_id_seq OWNER TO udacity;

--
-- Name: actors_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: udacity
--

ALTER SEQUENCE public.actors_id_seq OWNED BY public.actors.id;


--
-- Name: movies; Type: TABLE; Schema: public; Owner: udacity
--

CREATE TABLE public.movies (
    id integer NOT NULL,
    title character varying NOT NULL,
    release_date date
);


ALTER TABLE public.movies OWNER TO udacity;

--
-- Name: movies_id_seq; Type: SEQUENCE; Schema: public; Owner: udacity
--

CREATE SEQUENCE public.movies_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.movies_id_seq OWNER TO udacity;

--
-- Name: movies_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: udacity
--

ALTER SEQUENCE public.movies_id_seq OWNED BY public.movies.id;


--
-- Name: actors id; Type: DEFAULT; Schema: public; Owner: udacity
--

ALTER TABLE ONLY public.actors ALTER COLUMN id SET DEFAULT nextval('public.actors_id_seq'::regclass);


--
-- Name: movies id; Type: DEFAULT; Schema: public; Owner: udacity
--

ALTER TABLE ONLY public.movies ALTER COLUMN id SET DEFAULT nextval('public.movies_id_seq'::regclass);


--
-- Data for Name: actors; Type: TABLE DATA; Schema: public; Owner: udacity
--

COPY public.actors (id, name, age, gender) FROM stdin;
1	KamalHasan	67	Male
2	Vijay	46	Male
3	Nayanthara	31	Female
4	Vijay Sethupathi	40	Male
5	Dhanush	40	Male
6	Trisha	35	Female
7	Ajith	46	Male
\.


--
-- Data for Name: movies; Type: TABLE DATA; Schema: public; Owner: udacity
--

COPY public.movies (id, title, release_date) FROM stdin;
1	Shawshank Redemption	1994-12-28
2	Jigarthanda	2016-01-11
3	Soodhukavvum	2012-04-21
4	12 Angry Men	1970-02-17
5	Good Will Hunting	1990-11-05
6	C/O Kancharepalam	2018-04-10
\.


--
-- Name: actors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: udacity
--

SELECT pg_catalog.setval('public.actors_id_seq', 7, true);


--
-- Name: movies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: udacity
--

SELECT pg_catalog.setval('public.movies_id_seq', 6, true);


--
-- Name: actors actors_pkey; Type: CONSTRAINT; Schema: public; Owner: udacity
--

ALTER TABLE ONLY public.actors
    ADD CONSTRAINT actors_pkey PRIMARY KEY (id);


--
-- Name: movies movies_pkey; Type: CONSTRAINT; Schema: public; Owner: udacity
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

