"""empty message

Revision ID: 3030d9acffbd
Revises: 4562c4d4ab90
Create Date: 2020-05-21 10:47:56.238206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3030d9acffbd'
down_revision = '4562c4d4ab90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Person')
    op.drop_table('drink')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drink',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('recipe', sa.VARCHAR(length=180), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='drink_pkey'),
    sa.UniqueConstraint('title', name='drink_title_key')
    )
    op.create_table('Person',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Person_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('catchphrase', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Person_pkey')
    )
    op.drop_table('movies')
    op.drop_table('actors')
    # ### end Alembic commands ###
