"""empty message

Revision ID: 4562c4d4ab90
Revises: d96d4c5c94eb
Create Date: 2020-05-20 15:57:12.111403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4562c4d4ab90'
down_revision = 'd96d4c5c94eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drink', sa.Column('name', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drink', 'name')
    # ### end Alembic commands ###
